---
version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=995
      - PGID=995
      - TZ=America/Bahia
    volumes:
      - /data/sonarr/config:/config
      - /data/jellyfin/tv:/data/tv
      - /data/jellyfin/anime:/data/anime
      - /data/qbittorrent/downloads:/data/downloads
    ports:
      - 127.0.0.1:8989:8989
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true