---
version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=995
      - PGID=995
      - TZ=America/Bahia
    volumes:
      - /data/ombi/config:/config
    ports:
      - 127.0.0.1:3579:3579
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true