---
version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=995
      - PGID=995
      - TZ=America/Bahia
    volumes:
      - /data/readarr/data:/config
      - /data/booksonic/audiobooks:/data/audiobooks
      - /data/lazylibrarian/books:/data/books
      - /data/qbittorrent/downloads:/data/downloads
    ports:
      - 127.0.0.1:8787:8787
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true