---
version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=995
      - PGID=995
      - TZ=America/Bahia
    volumes:
      - /data/prowlarr/config:/config
    ports:
      - 127.0.0.1:9696:9696
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true