---
version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=995
      - PGID=995
      - TZ=America/Bahia
    volumes:
      - /data/lidarr/config:/config
      - /data/jellyfin/music:/data/music
      - /data/qbittorrent/downloads:/data/downloads
    ports:
      - 127.0.0.1:8686:8686
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true